name: Docker Image CI - Back

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build ./back --file ./back/Dockerfile --tag my-image-name:$(date +%s)
